version: 2
updates:
  # Docker base images
  - package-ecosystem: docker
    directories:
      - /versatiles
      - /versatiles-frontend
      - /versatiles-gdal
      - /versatiles-nginx
      - /versatiles-tilemaker
      - /versatiles-tippecanoe
    schedule:
      interval: weekly
    commit-message:
      prefix: "build(deps)"
    groups:
      docker:
        patterns: ["*"]

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "build(deps)"
    groups:
      github-actions:
        patterns: ["*"]
