version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule: { interval: monthly }
    groups: { github-action: { patterns: ['*'] } }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: monthly }
    groups: { github-action: { patterns: ['*'] } }
